### ISSUE TITLE
Stuck at solving environments on MSI stealth gaming pc, Nvidia rtx3060  8g ram windows 11. Any useful information will be appreciated

### ISSUE THREAD

**Issue by warmfart** [alievk/avatarify-desktop#49] opened 2023-04-11 21:26 UTC
Stuck at solving environments on MSI stealth gaming pc, Nvidia rtx3060  8g ram windows 11. Any useful information will be appreciated 

@JohanAR kindly drop the issue number or link to resolve this before subbing this issue as “duplicate”

**Comment by JohanAR** [comment] 2023-04-12 06:55
Well, now it's a duplicate of #47, which was open at the time you created a new report for the same issue.

Anyway, here's the link to the avatarify-python issue tracker: https://github.com/alievk/avatarify-python/issues/526

**Comment by davi0s** [comment] 2023-05-19 02:11
> Stuck at solving environments on MSI stealth gaming pc, Nvidia rtx3060 8g ram windows 11. Any useful information will be appreciated
> 
> @JohanAR kindly drop the issue number or link to resolve this before subbing this issue as “duplicate”

write me on here |
san.frdpatrick@gmail.com

**Closed as not planned** 2023-05-19 09:08 UTC
Labels: invalid

**Comment by davi0s** [comment] 2023-05-20 14:13
whatsapp
+234 811 513 3627
