### ISSUE TITLE
running slow on Mac using google lab

### ISSUE THREAD

**Issue by Chosenbrain** [alievk/avatarify-desktop#39] opened 2022-10-12 19:17 UTC
I used google lab but still running very slow after using the picture its keeps lagging and face not in order, how can you please help me

**Comment by JohanAR** [comment] 2022-10-12 19:39
If it's lagging it could be that your internet connection is too slow. If the face isn't detected properly, make sure that it fills most of the camera frame and that you have good lighting in your room.

**Comment by Chosenbrain** [comment] 2022-10-13 00:01
what about the face getting scattered/squeezed anytime I turned my face, how can I do it so my face would be static, if I get a virtual webcam will it help? thanks very much for the reply I really appreciate

**Comment by JohanAR** [comment] 2022-10-13 07:19
This part was a response to that:
> If the face isn't detected properly, make sure that it fills most of the camera frame and that you have good lighting in your room.

From your description it sounds like it has trouble consistently detecting your face. This is usually caused by there being too much noise in the image (solution: add more lamps or buy a better webcam) or the face being too small (solution: move the camera closer to your face)

**Comment by JohanAR** [comment] 2022-10-13 07:22
Wait a minute, this is the avatarify-desktop repo.. I thought I was replying to someone posting in the avatarify-python repo.. Avatarify-desktop only supports Windows, and does not work with remote GPU as far as I know. Did you create this issue in the wrong repo, or have you somehow managed to run the Windows app on a Mac?

**Comment by Chosenbrain** [comment] 2022-10-13 11:05
No sir,not avatarify desktop, i use google lab then open it on my terminal on mac,

**Comment by JohanAR** [comment] 2022-10-13 12:12
Ok, just checking. Previous comment about camera noise and framing is my best guess still

**Comment by Chosenbrain** [comment] 2022-10-13 14:56
Surely will check to that sir

**Comment by Chosenbrain** [comment] 2022-10-15 02:43
Thank you very much it worked perfectly fine but could not use it on telegram only on zoom, could not load the camera on telegram

**Comment by Fvrgo2800one** [comment] 2022-10-19 15:40
@Chosenbrain   hello brother, did you install the app on a MacBook?. If yes can you please share the link to the download page

**Comment by JohanAR** [comment] 2022-10-19 18:44
@Fvrgo2800one they did not. Maybe they didn't answer clear enough, but they're using avatarify-python and opened the issue in the wrong github project.

I'm closing this issue to avoid further confusion.

**Closed as completed by JohanAR** 2022-10-19 18:44 UTC
Labels: invalid
